# This is a basic workflow to help you get started with Actions

name: images-sync

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync-quay:
    runs-on: ubuntu-20.04
    container: setzero/images-sync:0.3.1
    env:
      TO_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      TO_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: sync quay images
        run: |
          cat << EOF >config.yaml
          from:
            registry: https://quay.io
          to:
            registry: https://registry.aliyuncs.com
          names:
            - cephcsi/cephcsi:v3.1.2
          replace:
            - old: cephcsi/
              new: it00021hot/
          rules:
            - ^[Vv]?\d+\.\d+(\.\d+)?(-\d+)?$
          EOF
          docker login --username ${{secrets.DOCKERHUB_USERNAME}} --password ${{ secrets.DOCKERHUB_TOKEN }} registry.cn-shenzhen.aliyuncs.com
          sync-images --config config.yaml
