name: choerodon

on:
  schedule:
    - cron: '0 0 8 * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync-choerodon:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      TO_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - name: Quay to Aliyun
      run: |
        cat << EOF >config.yaml
        registries:
          aliyuncs:
            registry: https://registry.aliyuncs.com
            username: $TO_USERNAME
            password: $TO_PASSWORD
          quay:
            registry: https://registry.cn-shanghai.aliyuncs.com
            repositories:
            - c7n/choerodon-register
            - c7n/choerodon-platform
            - c7n/choerodon-admin
            - c7n/choerodon-asgard
            - c7n/choerodon-gateway
            - c7n/choerodon-oauth
            - c7n/choerodon-iam
            - c7n/choerodon-file
            - c7n/choerodon-swagger
            - c7n/choerodon-message
            - c7n/choerodon-monitor
            - c7n/choerodon-front-hzero
            - c7n/choerodon-front
            - c7n/agile-service
            - c7n/knowledgebase-service
            - c7n/elasticsearch-kb
            - c7n/market-service
        sync-policy:
          from: quay
          to: aliyuncs
          dry-run: false
          replace:
            - old: c7n/
              new: mogu-zh/
          filters:
            - ^2\.\d+(\.\d+)?(-\d+)?$
        EOF
        registry-manager sync -c config.yaml
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 7
        keep_minimum_runs: 3
