name: docker

on:
  schedule:
    - cron: '0 0 8 * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync-docker:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      TO_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - name: docker hub to Aliyun
      run: |
        cat << EOF >config.yaml
        registries:
          aliyuncs:
            registry: https://registry.aliyuncs.com
            username: $TO_USERNAME
            password: $TO_PASSWORD
          docker:
            registry: https://docker.io
            repositories:
            # - bitnami/kafka
            # - bitnami/etcd
            - guiji2025/heygem.ai
            - guiji2025/fish-speech-ziming
            - guiji2025/fun-asr
        sync-policy:
          from: docker
          to: aliyuncs
          dry-run: false
          replace:
            # - old: bitnami/
              # new: it00021hot/bitnami_
            - old: guiji2025/
              new: it00021hot/guiji2025_
        EOF
        registry-manager sync -c config.yaml
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 7
        keep_minimum_runs: 3
