name: kaniko

on:
  schedule:
    - cron: '0 0 8 * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync-kaniko:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.HARBOR_USER }}
      TO_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - name: kaniko to Aliyun
        run: |
          cat << EOF >config.yaml
          registries:
            harbor:
              registry: https://imageharbor.xyz:38443
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://gcr.io
              repositories:
              - kaniko-project/executor
          sync-policy:
            from: gcr
            to: harbor
            dry-run: false
            replace:
              - old: kaniko-project/
                new: base/kaniko-
            filters:
              - '^[Vv]?([1-9]+)([2-9\.]+)(\.\d+){1,2}(-alpha\.\d+)?$'             
          EOF
          registry-manager sync -c config.yaml
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 7
          keep_minimum_runs: 3
