name: images-sync-px

on:
  schedule:
    - cron: '0 */2 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync-quay:
    runs-on: ubuntu-20.04
    container: setzero/images-sync:0.3.1
    env:
      TO_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      TO_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: sync quay images
        run: |
          cat << EOF >config.yaml
          from:
            registry: https://quay.io
          to:
            registry: https://registry.aliyuncs.com
          names:
            - k8scsi/csi-node-driver-registrar:v1.1.0
            - openstorage/csi-provisioner:v1.6.0-1
            - k8scsi/csi-snapshotter:v2.1.0
            - k8scsi/snapshot-controller:v2.1.0
            - k8scsi/csi-resizer:v0.5.0
            - coreos/prometheus-operator:v0.36.0
            - coreos/configmap-reload:v0.0.1
          replace:
            - old: k8scsi/
              new: px-k8scsi/
            - old: openstorage/
              new: openstorage/
            - old: coreos/
              new: px-k8scsi/
          rules:
            - ^[Vv]?\d+\.\d+(\.\d+)?(-\d+)?$
          EOF
          sync-images --config config.yaml

  sync-gcr:
    runs-on: ubuntu-20.04
    container: setzero/images-sync:0.3.1
    env:
      TO_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      TO_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: sync gcr images
        run: |
          cat << EOF >config.yaml
          from:
            registry: https://k8s.gcr.io
          to:
            registry: https://registry.aliyuncs.com
          names:
            - pause:3.1
            - kube-scheduler-amd64:v1.19.4
          replace:
            - new: ls-zh
          rules:
            - ^[Vv]?\d+\.\d+(\.\d+)?(-\d+)?$
          EOF
          sync-images --config config.yaml
