name: rook

on:
  schedule:
    - cron: '0 0 8 * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync-quay:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      TO_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - name: Quay to Aliyun
      run: |
        cat << EOF >config.yaml
        registries:
          aliyuncs:
            registry: https://registry.aliyuncs.com
            username: $TO_USERNAME
            password: $TO_PASSWORD
          quay:
            registry: https://quay.io
            repositories:
            - cephcsi/cephcsi
        sync-policy:
          from: quay
          to: aliyuncs
          dry-run: false
          replace:
            - old: cephcsi/
              new: it00021hot/
          filters:
            - ^[Vv]?\d+\.\d+(\.\d+)?(-\d+)?$
        EOF
        registry-manager sync -c config.yaml
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 7
        keep_minimum_runs: 3
  sync-gcr:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      TO_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - name: Gcr to Aliyun
      run: |
        cat << EOF >config.yaml
        registries:
          aliyuncs:
            registry: https://registry.aliyuncs.com
            username: $TO_USERNAME
            password: $TO_PASSWORD
          quay:
            registry: https://k8s.gcr.io
            repositories:
            - sig-storage/csi-node-driver-registrar
            - sig-storage/csi-attacher
            - sig-storage/csi-provisioner
            - sig-storage/csi-snapshotter
            - sig-storage/csi-resizer
        sync-policy:
          from: quay
          to: aliyuncs
          dry-run: false
          replace:
            - old: sig-storage/
              new: it00021hot/
          filters:
            - ^[Vv]?\d+\.\d+(\.\d+)?(-\d+)?$
        EOF
        registry-manager sync -c config.yaml

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 7
        keep_minimum_runs: 3
